table AMZN
	lineageTag: 54f206f9-86ca-4fb4-b050-a0881bbb1060

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8da68557-679c-44f8-8545-06a62ecb3787
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: d20fce5d-56cc-4a56-b8f5-245076983bd6
			defaultHierarchy: LocalDateTable_a65523f1-9184-4314-8daa-2413d5c19184.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: b6c7a304-4cea-45cd-8ef1-ad5ee7bac953
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: a738094e-a900-4fd0-927b-e3c2cdf9e596
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 98073956-f3a3-42b7-b6c9-2dd78dc818e3
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: c155bbc6-46b0-405e-af73-67fffc231d8f
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: 63609d89-0aaa-4cdc-9183-8f1828b596fa
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 8bf6969a-a540-4de2-88af-afb81715521a
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\PBI\PBIBroTraining\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

